### ISSUE TITLE
ng build error

### ISSUE THREAD

**Issue by yonus** [angelozerr/angular2-eclipse#12] opened 2016-06-29 06:29 UTC
Hello ,
I try to build by using  wizard ( run as ng buid)  ,  I get error  "Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat 'typings'
    at Error (native)"

thank your interest

**Comment by angelozerr** [comment] 2016-06-29 06:35
@yonus before posting to Angular2 Eclipse your problem, please:

 * check you have the same problem with you shell.
 * check in angular-cli that other people have the same problem than you.

It seems your problem is known. See 
https://github.com/angular/angular-cli/search?q=The+Broccoli+Plugin%3A+%5BFunnel%5D+failed+with%3A&type=Issues&utf8=%E2%9C%93

I close this issue since it's not a bug of Angular2 Eclipse.

**Closed by angelozerr** 2016-06-29 06:35 UTC

**Comment by yonus** [comment] 2016-06-29 06:43
I checked these problem  before , but I can't find the solution  so I  opened the issue.

**Comment by angelozerr** [comment] 2016-06-29 06:46
> I checked these problem before , but I can't find the solution so I opened the issue

As I said you, if you have problem with your shell, please post your issue at angular-cli project. Angular2 Eclipse consumes just angular-cli. If you have problem with your shell, you will have problem with Angular2 Eclipse terminal, wizards and launches.
