### ISSUE TITLE
Create new Angular project ==> The specified command init is invalid. For available options, see `ng help`.

### ISSUE THREAD

**Issue by javaspeak** [angelozerr/angular2-eclipse#69] opened 2017-04-03 07:02 UTC
Hi Angelo,

Thank you for your time.

I uninstalled the angular2-eclipse plugin in Neon and then installed the latest version:

     1.1.0.201611012218

I then chose in Eclipse:  File ==> New ==> Project ... ==> Angular 2 ==> Angular 2Project

On the console it ran until it stopped with the error:

    The specified command init is invalid. For available options, see `ng help`

For some reason it seems the plugin is calling an old method of ng which does not exist anymore.

If I open a terminal window and type:

    ng init

I will get the same error:

    The specified command init is invalid. For available options, see `ng help`

I have the same error whether I select:

     Preferences ==> JavaScript ==> TypeScript ==> Angular2 ==>Cli ==> Use global installation

or I select:

     Preferences ==> JavaScript ==> TypeScript ==> Angular2 ==> CLI ==> Use ng custom file

When I navigate to the directory where ng is and type ng --version I have:

    @angular/cli: 1.0.0
    node: 7.6.0

I am using a Mac.

Maybe I have misdiagnosed the problem but I suspect I have to wait for you to update your plugin to use @angular/cli 1.0.0.  It seems that version 1.0.0 does not have an init method.

What do you reckon?

I am new to a lot of this so maybe I am missing something :-)

I like eclipse for Java so I thank you for your work on this plugin to allow us to use Eclipse also for Angular 2 stuff.

Thank you

**Comment by angelozerr** [comment] 2017-04-03 07:06
Plase install 1.2.0-SNAPSHOT with update site https://github.com/angelozerr/angular2-eclipse/wiki/Installation-Update-Site (not released)

**Comment by javaspeak** [comment] 2017-04-03 07:55
Hi Angelo,

I have installed the 1.2.0-SNAPSHOT.

Now if I select "Use ng global installation" in preferences I see:

    The '/usr/local/lib/node_modules/@angular/cli/bin/ng' is not a ng file.

If I select "Use ng custom file" I get:

    The '/Users/javaspeak/workspaces/stuff/angula.../node_modules/@angular/cli/bin/ng' is not a ng file.

I did not have this problem when I installed the latest ( 1.1.0.201611012218).  I only have this problem with 1.2.0-SNAPSHOT (1.2.0.201704011024)

I am running on a mac so maybe stuff is working differently for you if you are on a different OS

Cheers

John

**Comment by Springrbua** [comment] 2017-04-06 07:05
@javaspeak The 1.1.0 version of the plugin won't work with Angular-CLI versions newer then beta.31.  
The Plugin used the CLI-Command "ng init" to initialize/create a project, but the command was removed in beta.32 (See [here](https://github.com/angular/angular-cli/blob/ed5f47dc22d5eb4a5d4b4ae2c8f7cb0ec1a999f3/CHANGELOG.md#code-refactoring)).

**Comment by javaspeak** [comment] 2017-04-07 06:08
@Springrbua Thanks for the explanation.  Maybe in the future, the plugin could inspect the version of CLI and call different commands depending on the version.  Thanks for your contributions and time.

**Comment by angelozerr** [comment] 2017-04-07 07:27
@javaspeak at first 1.2.0 is totally refactored because I use Terminal instead of console. Using Terminal provides a lot of improvement:

 * coloration in the console
 * interactive command (ex: if you generated an existing class, cli answer you if yiou wish to overide it)

When wizard opens terminal it updates the Path env with ng path dir and node path dir.

The original issue is to specify ng. I have try to fix this issue. Please reinstall 1.2.0 and tell me if it works now.

For the support of ng init, I would like to avoid supporting that since cli was released and doesn't provide ng init.

**Comment by Springrbua** [comment] 2017-04-07 09:18
@javaspeak The Angular-CLI is now in a stable version, which means there shouldn't be breaking changes like that in future and I wouldn't support CLI-Versions < 1.0 (there is no reason to use Angular-CLI beta or RC-Versions, when stable version is released).  
That means, that for now there is no reason to track the CLI-Version and execute different commands.  
Maybe they will add new commands, parameters etc. in future and then we might need to think about tracking CLI-Version and customize the Wizards depending on that version.

**Comment by javaspeak** [comment] 2017-04-07 10:23
@angelozerr I installed 1.2.0.201704061424 of the plugin on a Mac.

However on creating a new Angular2 project it is not displayed in the package explorer at the end of the project creation process:

This is what I did and what happened:

In Eclipse CLI preferences I set "Use ng custom installation" to:

    /usr/local/bin

The CLI path showed:

    /usr/local/lib/node_modules/@angular/cli/bin/ng

Then I created a new Angular2 project from the File menu.

In the eclipse terminal I can see:

    bash-3.2$ PS1='\w\$ '
    ~/workspaces/eclipse-angular-plugin$ 
    ~/workspaces/eclipse-angular-plugin$ /usr/local/bin/ng new tryout

    installing ng
      create .editorconfig
      create README.md
      create src/app/app.component.css
      create src/app/app.component.html
      create src/app/app.component.spec.ts
      create src/app/app.component.ts
      create src/app/app.module.ts
      create src/assets/.gitkeep
      create src/environments/environment.prod.ts
      create src/environments/environment.ts
      create src/favicon.ico
      create src/index.html
      create src/main.ts
      create src/polyfills.ts
      create src/styles.css
      create src/test.ts
      create src/tsconfig.app.json
      create src/tsconfig.spec.json
      create src/typings.d.ts
      create .angular-cli.json
      create e2e/app.e2e-spec.ts
      create e2e/app.po.ts
      create e2e/tsconfig.e2e.json
      create .gitignore
      create karma.conf.js
      create package.json
      create protractor.conf.js
      create tsconfig.json
      create tslint.json
    Successfully initialized git.
    Installing packages for tooling via npm.
    Installed packages for tooling via npm.
    Project 'tryout' successfully created.
    ~/workspaces/eclipse-angular-plugin$ 
l
The project "tryout" completed successfully according to the eclipse terminal.  However at the end there is no project in Eclipse's Project view.

If I then try and go and create a new Angular2 project again with the same name it says in the eclipse terminal window:

    Directory /Users/johndickerson/workspaces/eclipse-angular-plugin/tryout exists and is already an Angular CLI project.

If I close eclipse and open it again there is still no "tryout" project in the Project Explorer.

I then looked at the file system and saw no eclipse project files:

    $ ls -ltra
    total 88
    -rw-r--r--    1 javaspeak  staff   2710 Apr  7 12:58 tslint.json
    -rw-r--r--    1 javaspeak  staff    385 Apr  7 12:58 tsconfig.json
    drwxr-xr-x   14 javaspeak  staff    476 Apr  7 12:58 src
    -rw-r--r--    1 javaspeak  staff    756 Apr  7 12:58 protractor.conf.js
    -rw-r--r--    1 javaspeak  staff   1199 Apr  7 12:58 package.json
    -rw-r--r--    1 javaspeak  staff   1240 Apr  7 12:58 karma.conf.js
    drwxr-xr-x    5 javaspeak  staff    170 Apr  7 12:58 e2e
    -rw-r--r--    1 javaspeak  staff   1081 Apr  7 12:58 README.md
    -rw-r--r--    1 javaspeak  staff    516 Apr  7 12:58 .gitignore
    drwxr-xr-x   13 javaspeak  staff    442 Apr  7 12:58 .git
    -rw-r--r--    1 javaspeak  staff    245 Apr  7 12:58 .editorconfig
    -rw-r--r--    1 javaspeak  staff   1124 Apr  7 12:58 .angular-cli.json
    drwxr-xr-x    5 javaspeak  staff    170 Apr  7 12:58 ..
    drwxr-xr-x   16 javaspeak  staff    544 Apr  7 13:02 .
    drwxr-xr-x  746 javaspeak  staff  25364 Apr  7 13:03 node_modules
    -rw-r--r--@   1 javaspeak  staff   6148 Apr  7 13:03 .DS_Store

Maybe I downloaded the wrong version of the plugin.  I downloaded from:

    http://oss.opensagres.fr/angular2-eclipse/1.2.0-SNAPSHOT/
    version:  1.2.0.201704061424

**Comment by angelozerr** [comment] 2017-04-07 12:01
It seems that you have checked "Execute ng file". If I remember, I have not managed refresh of project with this option. It's on my TODO list. Could you try please without checking this option please.

**Comment by Springrbua** [comment] 2017-04-07 12:07
@javaspeak Thats the exactly same problem I had previously (Posted an Issue [here](https://github.com/angelozerr/typescript.java/issues/162))  
The problem seems to be resolved for me with the newest version of the plugin.  
Please try to do a "check for updates" and download the latest version of the plugins (Angular2-Eclipse + typescript.java).  
If there is no newer version or the problem is the same with the new version, then the Terminal probably has problem on Mac. I am using Windows 10, so I can't verify that...  

However, you can continue to work with the plugin, even if you still have this problem:  
1) Generate a Angular2 Project. It won't be added to workspace, but it will be created on disk.
2) Create a new Project using "File > New > Project".
3) In the Wizard select "General > Project"
4) Name the Project (I would use the same name as before) and select the folder with the .angular-cli.json file
5) Finish  

You should now have the Angular project in your workspace.  
If you create components, you might have the refresh-problem too, so you would need to manually refresh the project to see the newly generated files.

**Comment by angelozerr** [comment] 2017-04-07 12:20
@Springrbua it seems @javaspeak uses the last version of Angular2 Eclipse. I think the problem comes from "Execute ng file".

**Comment by Springrbua** [comment] 2017-04-07 12:56
@angelozerr I already saw that his Angular2-Eclipse version is the newest (same as my installed version).  
I just wasn't sure if typescript.java (which containts the Terminal-Logic as much as I know) is automatically up to date too.  
Thats why I suggested to check for updates again.  
I never tryed the "Execute ng file" option, so I can't yet tell you if that works for me. I always use the global installation.

**Comment by javaspeak** [comment] 2017-04-07 13:43
@angelozerr If I uncheck "Execute ng file" click apply and ok and then open the CLI preferences again "Execute ng file" is checked again.

**Comment by javaspeak** [comment] 2017-04-07 13:44
@Springrbua thanks for the tip, will try

**Comment by angelozerr** [comment] 2017-04-07 13:58
> @angelozerr If I uncheck "Execute ng file" click apply and ok and then open the CLI preferences again "Execute ng file" is checked again.

Yes it's a bug, I will fix it.

You can change this value at hand: open .settings\ts.eclipse.ide.angular2.cli.prefs file from your project (use Navigator View to see .settings) and change 

`executeNgWithFile=false`

**Comment by javaspeak** [comment] 2017-04-07 14:05
@Springbua The tip for opening the existing project as a General Project worked. Thanks.  Then I created a component and when doing a refresh on the project I could see the component.  Thanks.

However the .angular-cli.json file is not visible so one cannot do stuff like editing the styles section of the json file while in eclipse.  Maybe .angular-cli.json is shown in The Angular2 project.

Anyway I will wait for a release version - thanks again.

**Comment by angelozerr** [comment] 2017-04-07 14:07
> However the .angular-cli.json file is not visible 

Use Navigator View. By default Package Explorer hides the whole files which starts with dot. I don't know if we can override that?

**Comment by Springrbua** [comment] 2017-04-07 14:23
@javaspeak @angelozerr The Project-Explorer by default hides all Files starting with ".".
You can disable this filter by clicking on the small arrow on the top left of the project explorer and go to "Customize View".  
In the Filter-Tap you need to uncheck the ".* resources" entry. Now all Files starting with "." will be visible (including .angular-cli.json, but also .project file...)

**Comment by javaspeak** [comment] 2017-04-07 15:20
@angelozerr 

Re your comment: 

    You can change this value at hand: open .settings\ts.eclipse.ide.angular2.cli.prefs file 
    from your project (use Navigator View to see .settings) and change

On my mac I do not have .settings under my project. 

I did find a .settings under my workspace directory hidden away in a .metadata folder:

    .metadata/.plugins/org.eclipse.core.runtime/.settings/ts.eclipse.ide.angular2.cli.prefs

I added:

    executeNgWithFile=false

to the ts.eclipse.ide.angular2.cli.prefs file.

When I restarted eclipse I saw the "Execute ng file" checkbox under CLI preferences (Eclipse:Preferences:Javascript:TypeScript:Angular2:CLI ) was unchecked as you said  :-)

I then created a new Angular2 project and as you indicated, this time I could see the Angular2 project in the eclipse project explorer. When "Execute ng file" is unchecked it works for me :-)

I am not sure what the "Execute ng file" checkbox is meant for anyways. Maybe a help button with a popup could help people like me. Often people who know less about a new technology start using plugins and IDEs as it can be easier at the beginning.

I guess stuff is a bit different on different OS's when it comes to the file system.  However one could try out a plugin on different OS like Mac using Virtual Box.  Mac OS is a bit tricky to install on Virtual Box but one could install Hackintosh.  There are Yosemite versions of Hackintosh.   You can download the Hackintosh image from here:

https://www.hackintosh.zone/file/810-nireshs-yosemite-with-amd-intel-iso-usb/

I never run Hackintosh in virtual box myself as I have a Mac. I have run other OS when I need to test stuff. There is a youtube video which shows installing Hakintosh on virtual box:

https://www.youtube.com/watch?v=i-9m9Z63kR4

I think I will not pester you guys until there is a release - then any bug finding by me will help.  At the moment I am wasting time because not everything has been done yet so it is normal I find issues.

I do not know enough about creating eclipse plugins to help your guys so it is best I hang on a bit before being useful with testing releases.

Thank you

**Comment by javaspeak** [comment] 2017-04-07 15:24
@Springrbua Thanks about default hide tip of Project Explorer of Eclipse

**Comment by Springrbua** [comment] 2017-04-07 15:41
@javaspeak Please continue to post any bug you find and any feature you are missing.  
We certainly don't know any environments and use-cases, so any feedback of testers is very usefull.

**Comment by angelozerr** [comment] 2017-04-09 19:05
@javaspeak I have fixed little bug like preferences executeNgWithFile which can be checked and now executeNgWithFile should work (refresh the project)

I close this issue. Any feedback are welcome @javaspeak !

**Closed by angelozerr** 2017-04-09 19:05 UTC
