### ISSUE TITLE
eclipse angular2 project creating error

### ISSUE THREAD

**Issue by yonus** [angelozerr/angular2-eclipse#11] opened 2016-06-27 22:04 UTC
Hello ,
When I try to create angular2 project in eclipse , I get following error:

module.js:327
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pasa/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
'unknown': unknown terminal type.

**Comment by angelozerr** [comment] 2016-06-28 08:28
@yonus your issue is about angular-cli. See https://github.com/angular/angular-cli/issues/1186

In my case I have fixed the problem by following comments https://github.com/angular/angular-cli/issues/1186#issuecomment-228364667

Before creating issue here, I suggest you that you try before with your CLI (MS-DOS or other according your OS).

Please note that I will provide soon Wizards to consumes angular-cli.

I close this issue since it's not a bug of Angular2 Eclipse.

**Closed by angelozerr** 2016-06-28 08:28 UTC
